export const LOGIN = "ADMIN_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const ADD_APARTMENT = "ADD_APARTMENT";
export const ADD_APARTMENT_ERROR = "ADD_APARTMENT_ERROR";

export const GET_ALL_APARTMENT = "GET_ALL_APARTMENT";
export const GET_ALL_APARTMENT_ERROR = "GET_ALL_APARTMENT_ERROR";
